# This file describes a conda environment that can be used by alpha testers
#
# Run the following command to set up this environment:
# $ conda env create -f test_environment.yml
#
# The environment name can be overridden with the following command:
# $ conda env create -n <custom name> -f test_environment.yml
#
# Run the following command to activate the environment:
# $ source activate cvxportfolio-testing
#
# To deactivate the environment run the following command:
# $ source deactivate
#
# To remove the environment entirely, run the following command:
# $ conda env remove -n cvxportfolio-testing

name: cvxportfolio-testing
channels:
  - cvxgrp
dependencies:
  - python=3.6
  - pandas
  - cvxpy
  - matplotlib
  - jupyter
  - pytables
  - nose